[general]
# default_palette = "combine"
default_palette = "commands"
default_frontend = "fzf"


[palette]

  [palette.combine]
  base = "combine"
  cache = true
  include = ["palettes", "commands"]

  [palette.palettes]
  base = "palettes"

  [palette.apps]
  base = "apps"

  [palette.commands]
  auto_list = true
  data = "~/datas/commands.json"

  [palette.psg]
  base = "builtin/psg"
  auto_pick = true

  [palette.psgv2]
  base = "github.com/zcag/palplugins/psg/psg"
  auto_pick = true


[frontend]

  [frontend.fzf]
  bin = "fzf"
  args = []

  [frontend.rofi]
  bin = "rofi"
  args = ["-normal-window"]
