[general]
default_palette = "pals"
default_frontend = "fzf"

[palette]
  [palette.pals]
  base = "builtin/palettes/pals"

  [palette.combine]
  base = "builtin/palettes/combine"
  include = []

# Frontends need to be configured - see examples/
[frontend]
