[general]
default_palette = "pals"
default_frontend = "fzf"

[palette]
  [palette.pals]
  base = "builtin/palettes/pals"

  [palette.combine]
  base = "builtin/palettes/combine"
  include = []

[frontend]
  [frontend.fzf]
  base = "builtin/frontends/fzf"

  [frontend.rofi]
  base = "builtin/frontends/rofi"

  [frontend.stdin]
  base = "builtin/frontends/stdin"
