[palettes.apps]
name = "apps"
desc = "list and launch applications"
version = "0.1"
contract_version = "0.0.1"

[palettes.bookmarks]
name = "bookmarks"
desc = "list and open browser bookmarks"
version = "0.1"
contract_version = "0.0.1"

[palettes.pals]
name = "pals"
desc = "list and run palettes"
version = "0.1"
contract_version = "0.0.1"

[palettes.psg]
name = "psg"
desc = "list and kill processes"
version = "0.1"
contract_version = "0.0.1"

[palettes.combine]
name = "combine"
desc = "combine multiple palettes"
version = "0.1"
contract_version = "0.0.1"

[frontends.fzf]
name = "fzf"
desc = "fzf fuzzy finder frontend"
version = "0.1"
contract_version = "0.0.1"

[frontends.rofi]
name = "rofi"
desc = "rofi launcher frontend"
version = "0.1"
contract_version = "0.0.1"

[frontends.stdin]
name = "stdin"
desc = "simple stdin/stdout frontend"
version = "0.1"
contract_version = "0.0.1"
